### ISSUE TITLE
Permissions of google drive link

### ISSUE THREAD

**Issue by ylabbe** [r-pad/zephyr#5]
Hi, thank you for sharing this great work!
I want to access your preprocessed data using the provided link [https://drive.google.com/drive/folders/1Fq-24RAnn0uWAEVauwMZgpqtWYkZCqQI?usp=sharing](https://drive.google.com/drive/folders/1Fq-24RAnn0uWAEVauwMZgpqtWYkZCqQI?usp=sharing) but it is not accessible.
Is it normal ? Otherwise, could you please make the data public ?
Thanks!

**Comment by georgegu1997** [comment]
Hi Yann, Thanks for your interest! 

Sorry for the broken link. We just updated the [link](https://drive.google.com/drive/folders/1ZdTHK10_8ezWtSGblYYVMrQr17gXcH7W?usp=sharing) and can you try this again?

**Comment by yannlabb** [comment]
It works. Great, thanks!
