### ISSUE TITLE
Pose hypotheses using SIFT

### ISSUE THREAD

**Issue by manuelli** [r-pad/zephyr#6]
Hi,

Thanks for the great work. We are doing some benchmarking and would like to use the same set of pose hypotheses that were used in the paper. The hypotheses from the Drost PPF method are available in the google drive link you shared. Are the Dense SIFT hypotheses for YCBV also precomputed and available somewhere?

Thanks!

**Comment by georgegu1997** [comment]
Hi, 

I think you can find all the hypotheses in `ycbv_preprocessed.zip`. The folder structure and the content can be found [here](https://github.com/r-pad/zephyr/blob/main/python/zephyr/data_util.py#L11). For YCB-V, there should be 1101 hypotheses for each object in a scene. The first 100 come from the PPF results, the middle 1000 are sampled dense SIFT matching and the last 1 is an oracle (GT or closest to GT) pose hypothesis, which was removed from our evaluation. (more details can be found [here](https://github.com/r-pad/zephyr/blob/main/python/zephyr/full_pipeline/main.py#L69))

Thanks!

**Comment by manuelli** [comment]
Thanks for the information. I was able to extract the poses.
