### ISSUE TITLE
Format of PPF pose hypotheses

### ISSUE THREAD

**Issue by manuelli** [r-pad/zephyr#7]
I had a question about the format of the pose hypotheses generated by the PPF algorithm. I downloaded the  `ycb_list_bop_test.txt` file from the google drive. The first two lines are

```
ObjectId	SceneId	ImageId	Score	XTrans	YTrans	ZTrans	XRot	YRot	ZRot	Type	Time
1	48	1	0.068509	-31.601661	-15.736851	868.440547	102.314703	359.950180	194.663570	0	183.536200
```

I had a few questions.
1. I am assuming that translation is expressed in millimeters correct?
2. XRot,YRot,ZRot are euler angles in degrees presumably. Which convention are they following. I am assuming it is the `XYZ` convention as defined in [`scipy.Rotation`].(https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_euler.html)
3. I assume that this is the `object_to_camera` transform correct?

**Comment by georgegu1997** [comment]
Hi, 

Please refer [here](https://github.com/r-pad/zephyr/blob/f5f134728107a7a9e36c6292fecb2a58e81443ec/python/zephyr/utils/bop_dataset.py#L259) for how to read the PPF hypotheses from txt file. 

For the thrid question, yes, it should have the same meaning as "m2c" [here](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_datasets_format.md#ground-truth-annotations). 

Thanks!

**Comment by manuelli** [comment]
Thanks for the detailed response.
