### ISSUE TITLE
How to predict the pose of an custom object？ Could you please provide a tutorial！！

### ISSUE THREAD

**Issue by lunalulu** [r-pad/zephyr#8]
thank you very much!!

**Comment by lunalulu** [comment]
@georgegu1997

**Comment by georgegu1997** [comment]
Please check out the [TestExample.ipynb](https://github.com/r-pad/zephyr/blob/main/notebooks/TestExample.ipynb) for how to use the trained network to estimate object pose. For new objects, a colored mesh model is required. The sampled point cloud with per-vertex color and normal vector can be obtained by [pcl_mesh_sampling](https://github.com/PointCloudLibrary/pcl/blob/master/tools/mesh_sampling.cpp#L189).

**Comment by lunalulu** [comment]
@georgegu1997 thank you very much!!
